# 写一个github的action，用于更新readme.md文件，然后再推送到仓库里。
name: Update README
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:                              # 其中一个任务的名称，ID
    runs-on: ubuntu-latest                       # 这个任务运行所需的环境
    steps:
      - name: Checkout                           # 第一步：获取源码
        uses: actions/checkout@v3                # 使用的工具

      - name: 更新readme.md                      # 第二步：下载依赖和构建
        run: |
          node -v
          node update-readme.js

      - name: 推送新的readme.md到远端
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "update readme.md"
          git push origin master
